### ISSUE TITLE
tabSignal.connect is not a function

### ISSUE THREAD

**Issue by akaDJon** [CppComet/comet-server#34]
Ошибка "tabSignal.connect is not a function" выходит только на Опере (хотя может и еще где), в Хроме и Фаере ее нету. 

Анализ показал что tabSignal.connect undefined для Оперы

**Comment by Levhav** [comment]
Какая версия оперы у вас. Я проверил в старой версии 12.16 и там ошибка не воспроизвелась.

Build:1860, Platform:Linux  System: x86_64, 3.13.0-101-generic 
Opera/9.80 (X11; Linux x86_64) Presto/2.12.388 Version/12.16
