### ISSUE TITLE
_cometServerApi.prototype.send_msg("pipe_log\n"+pipe_name+"\n"+marker+"\n");

### ISSUE THREAD

**Issue by akaDJon** [CppComet/comet-server#35]
На новой версии CometServerApi.js перестает работать subscription из-за 
`_cometServerApi.prototype.send_msg("pipe_log\n"+pipe_name+"\n"+marker+"\n");`

Судя по коду marker не инициализируется если callBack не задан

возврат к старой версии `_cometServerApi.prototype.send_msg("pipe_log\n"+pipe_name+"\n"+_cometServerApi.prototype.custom_id+"\n");` решает проблему

**Comment by Levhav** [comment]
Спасибо за сообщение. Скоро посмотрю. Пока я не решил проблему вы можете использовать предыдущею версию CometServerApi.js она должны быть совместима последней версией сервера.
