### ISSUE TITLE
CometServerApi.js:824 Invalid pipe name subscription web_chat_pipe chatControl

### ISSUE THREAD

**Issue by akaDJon** [CppComet/comet-server#36]
При обновлении slave вкладки на master вкладке выходит ошибка
CometServerApi.js:824 Invalid pipe name subscription web_chat_pipe chatControl

Я так понял что слейв говорит мастеру на что ему нужно подписаться.

Добавил в _cometServerApi.prototype.subscription

> console.log('subscription: ', name);

и увидел следующую картину:
при инициализации мастера:

```
subscription:  web_chat_pipe.msg
subscription:  answer_to_web_chat_pipe
subscription:  chatControl.clean
```
а после обновления слейва в мастере вот это:
```
subscription:  subscription
web_chat_pipe
chatControl

Invalid pipe name subscription
web_chat_pipe
chatControl

```

видимо слейв отдает мастеру все подписки одним текстом да еще и в урезанном виде.

**Comment by akaDJon** [comment]
И кстати еще по Invalid pipe name
CometServer().subscription("#Имя_канала", function(e){ console.log(e)})
не пройдет валидацию в regexp `/^[A-z0-9_.\-]+$/`
Там нужен `/^[A-z0-9_.\-\#]+$/`

**Comment by Levhav** [comment]
> И кстати еще по Invalid pipe name
CometServer().subscription("#Имя_канала", function(e){ console.log(e)})
не пройдет валидацию в regexp /^[A-z0-9_.\-]+$/
Там нужен /^[A-z0-9_.\-\#]+$/

Символ # это короткая запись на вызов CometServer().subscription("answer_to_Имя_канала", function(e){ console.log(e)}) по этому он на сервер не отправляется.

**Comment by Levhav** [comment]
Мне было бы проще воспроизвести проблему где то в вашем окружении, а не пытаться смоделировать те же условия локально. У вас этот код с ошибкой где то доступен в интернете? Если не хотите публиковать реквизиты доступа здесь то можете отправить их мне на почту Levhav@yandex.ru

**Comment by akaDJon** [comment]
> Символ # это короткая запись на вызов CometServer().subscription("answer_to_Имя_канала", function(e){ console.log(e)}) по этому он на сервер не отправляется.
Проверка /^[A-z0-9_.-]+$/ в JS находится и она и ругается

**Comment by akaDJon** [comment]
Написал на почту ссылку на тест
