### ISSUE TITLE
Функция приватного доступа в чат доступный пользователям только для чтения

### ISSUE THREAD

**Issue by akaDJon** [CppComet/comet-server#37]
Вопрос в том можно ли запретить (защитить общий канал) от отправки в него сообщений из вне (из JS)
Например я хочу при необходимости вывести у всех пользователей сразу сообщение "Через 15 минут сайт закрывается на техническое обслуживание. Сохраните документы с которыми работаете и выйдите из системы". Но мне нужно гарантировать что никак кроме как из моего PHP (CometQL) подобный сигнал не будет отправлен пользователям. 
Сейчас насколько я понял общие каналы (без авторизации) открыты и на чтение и на запись одновременно и при желании какой нибудь хакер может отправить в него чтонибудь свое)

**Comment by Levhav** [comment]
Из JavaScript API можно отправить сообщение в канал только если имя канала начинается на web_* в остальные каналы можно отправлять данные только из CometQL
Список каналов с особыми свойствами опубликован тут https://comet-server.com/wiki/doku.php/comet:javascript_api:pipe-types
