### ISSUE TITLE
cmake syntax error

### ISSUE THREAD

**Issue by mrTigerFox** [CppComet/comet-server#4]
yacc: e - line 112 of "src/CometQL.y", syntax error
%lex-param      { void* qInfo }

**Comment by Levhav** [comment]
hello. can you add full cmake output and information about operating system?

**Comment by mrTigerFox** [comment]
[cmake.zip](https://github.com/CppComet/comet-server/files/1130182/cmake.zip)

**Comment by Levhav** [comment]
In the log files that you sent is not mentioned something that looks like
> yacc: e - line 112 of "src/CometQL.y", syntax error

But it is visible that cmake does not find pthreads
Try installing the package

> yum install glibc-static

**Comment by mrTigerFox** [comment]
i was install glibc-static package, but a have same error.
[cmake_.zip](https://github.com/CppComet/comet-server/files/1130306/cmake_.zip)

**Comment by Levhav** [comment]
And what conclusion do you have in the console when trying to compile?

**Comment by Levhav** [comment]
I can assume that you do not have enough new version of the compiler. Recently, I tested the assembly only in CentOS 7

**Comment by mrTigerFox** [comment]
# cmake .
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- System: Linux 2.6.32-042stab113.21
-- Processor: x86_64
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
yacc: e - line 112 of "src/CometQL.y", syntax error
%lex-param      { void* qInfo }
^
Usage: yacc [options] filename

Options:
  -b file_prefix        set filename prefix (default "y.")
  -d                    write definitions (y.tab.h)
  -g                    write a graphical description
  -l                    suppress #line directives
  -o output_file        (default "y.tab.c")
  -p symbol_prefix      set symbol prefix (default "yy")
  -r                    produce separate code and table files (y.code.c)
  -t                    add debugging support
  -v                    write description (y.output)
  -V                    show version information and exit
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MYSQL_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /u01/www/bwru.ru/comet-server

-- Configuring incomplete, errors occurred!
See also "/u01/www/bwru.ru/comet-server/CMakeFiles/CMakeOutput.log".
See also "/u01/www/bwru.ru/comet-server/CMakeFiles/CMakeError.log".

**Comment by Levhav** [comment]
By default, CentOS 6.x does not contain a compiler supporting C++11 
you need try install gcc  with version 4.9 or later or update system to CentOS 7 
At the moment for CentOS 6 will only critical updates are released, full support has already ended 10 May 2017

**Comment by mrTigerFox** [comment]
it so sad, but i cant upgrade server right now.
Thank U for your support.

Спасибо)

**Comment by Levhav** [comment]
you can try update only gcc to 4.9 on server, try search 'centos 6 c++11'

обращайтесь, если какие то ещё вопросы буду :)

**Comment by Levhav** [comment]
Ещё заметил у вас такую проблему что вы положили конфиги комет сервера в доступную через веб папку. Запрос к http://bwru.ru/comet-server/comet.ini позволяет скачать ваш конфиг с паролями к комет серверу. 
К сожалению ни каких других способов связаться с вами у вас в профиле я не нашёл.
