### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by mrTigerFox** [CppComet/comet-server#53]
root@v42471: /comet-server# make
[  2%] Building CXX object CMakeFiles/cppcomet.dir/src/main.cpp.o
In file included from /root/comet-server/dependencies/jwt-cpp/src/include/jwt/claimvalidator.h:26:0,
                 from /root/comet-server/dependencies/jwt-cpp/src/include/jwt/jwt.h:31,
                 from /root/comet-server/dependencies/jwt-cpp/src/include/jwt/jwt_all.h:26,
                 from /root/comet-server/src/internalApi.h:20,
                 from /root/comet-server/src/user_index.h:27,
                 from /root/comet-server/src/devManager.h:11,
                 from /root/comet-server/src/main.cpp:17:
/root/comet-server/dependencies/jwt-cpp/src/include/jwt/json.hpp: In function ‘bool nlohmann::operator<(nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::const_reference, nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::const_reference)’:
/root/comet-server/dependencies/jwt-cpp/src/include/jwt/json.hpp:5704:50: error: wrong number of template arguments (1, should be 2)
         return *lhs.m_value.array < *rhs.m_value.array;
                                                  ^~~~~
In file included from /usr/include/c++/7/tuple:39:0,
                 from /usr/include/c++/7/bits/stl_map.h:63,
                 from /usr/include/c++/7/map:61,
                 from /root/comet-server/src/TagTimer.h:8,
                 from /root/comet-server/src/main.h:131,
                 from /root/comet-server/src/main.cpp:14:
/usr/include/c++/7/array:94:12: note: provided for ‘template<class _Tp, long unsigned int _Nm> struct std::array’
     struct array
            ^~~~~
CMakeFiles/cppcomet.dir/build.make:158: recipe for target 'CMakeFiles/cppcomet.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/cppcomet.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cppcomet.dir/all' failed
make[1]: *** [CMakeFiles/cppcomet.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Levhav** [comment]
Hi, what version of gcc, cmake and operating system you use?

**Comment by mrTigerFox** [comment]
Ubuntu 18.04 LTS
cmake version 3.10.2
gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0

**Comment by mrTigerFox** [comment]
i can grant you SSH access to server if it need for localise problem

**Comment by Levhav** [comment]
Yes, it will be helpful. You can send message to Levhav@ya.ru

**Comment by mrTigerFox** [comment]
i just made answer to you at email.
Thanks a lot
